// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/athunlal/bookNowBooking-svc/pkg/api"
	"github.com/athunlal/bookNowBooking-svc/pkg/api/handler"
	"github.com/athunlal/bookNowBooking-svc/pkg/config"
	"github.com/athunlal/bookNowBooking-svc/pkg/db"
	"github.com/athunlal/bookNowBooking-svc/pkg/repository"
	"github.com/athunlal/bookNowBooking-svc/pkg/usecase"
	"github.com/athunlal/bookNowBooking-svc/pkg/usermodule"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHttp, error) {
	database, err := db.ConnectDataBase(cfg)
	if err != nil {
		return nil, err
	}
	client := usermodule.UserModule(&cfg)
	bookingRepo := repository.NewTrainRepo(database)
	bookingUseCase := usecase.NewBookingUseCase(bookingRepo,client)
	bookingHandler := handler.NewBookingHandler(bookingUseCase)
	serverHttp := api.NewServerHttp(bookingHandler)
	return serverHttp, nil
}
